Use standard input to read local script
Avoids:
```
ERROR: This command is requesting the deprecated -remoting
mode. See https://jenkins.io/redirect/cli-command-requires-channel
```
https://issues.jenkins-ci.org/browse/JENKINS-45625